server:
  port: 1061

spring:
  data:
    mongodb:
      host: 10.1.20.8
      port: 27017
      database: cache
dubbo:
  registries:
    - address: 10.1.1.153
      protocol: zookeeper
  services:
    - interface: com.dxhy.platform.data.mongo.api.InvoiceMongoDBSaveService

dxhy:
  mongo:
    index:
      - clazz: com.dxhy.platform.data.mongo.api.bean.InvoiceCache
        indexName: createTime
        direction: ASC
        expireTime: 10
        timeUnit: DAYS
